map $uri $cache_control {
  # A sensible default cache policy for all other files
  # We want to make sure that all files are cached for a short period of time
  # to improve performance, but also be in control rather than relying on browser defaults
  default "max-age=300, must-revalidate";

  # Cache-control for index.html and environment.js
  # We want to make sure index.html and environment.js are never cached, so that users always
  # get the latest version of the application and environment configuration
  ~*/index\.html$ "private, no-cache, no-store, must-revalidate";
  ~*/environment\.js$ "private, no-cache, no-store, must-revalidate";

  # Cache .json files for 5 minutes
  # These files are used for static translations, we want to make sure
  # they are not cached for too long in case of missing or wrong strings
  ~*\.json$ "max-age=300, public";

  # Cache other static files (e.g., .png, .jpg, .svg, etc.) for 30 minutes
  # These files are not changing frequently, and caching them improves performance
  ~*\.(png|jpg|jpeg|svg|gif|ico)$ "max-age=1800, public";

  # Cache .js, .css, and font files for 4 hours
  # Application .js, .css, and font files are hashed and never change, and when a new app version
  # is deployed, we want to make sure the old hashes are still cached in case of users
  # having an older version of index.html in their cache and trying to fetch these old files
  ~*\.(js|css|woff|woff2|ttf|eot)$ "max-age=14400, public";
}

server {
  listen       80 default_server;
  listen  [::]:80 default_server;

  location / {
    root      /usr/share/nginx/html/webapp;
    try_files $uri $uri/ $uri.html /index.html;
    add_header Cache-Control $cache_control;
  }
}

server {
  listen       80;
  listen  [::]:80;
  server_name  localhost *.private.wiley.host;

  location /storybook {
    root /usr/share/nginx/html;
    index index.html;
  }

  location / {
    root      /usr/share/nginx/html/webapp;
    try_files $uri $uri/ $uri.html /index.html;
    add_header Cache-Control $cache_control;
  }
}
