services:
  app:
    hostname: flag-football-analyzer
    network_mode: host
    build:
      context: ../
      dockerfile: ./.devcontainer/development.dockerfile
    volumes:
      - '../:/app'
      - '/app/node_modules'
    stdin_open: true
    tty: true
